#
# Use winver to check whether your Windows Host OS is >= 1909
# If not, use the appropriate version
#
FROM mcr.microsoft.com/windows:1909



#
# Configure Powershell as the Default Shell
#
SHELL ["PowerShell", "-NoProfile", "-Command", "$ErrorActionPreference = 'Stop';"]
CMD PowerShell.exe



#
# Install Firefox
#
ADD https://ftp.mozilla.org/pub/firefox/releases/58.0.2/win64/en-US/Firefox%20Setup%2058.0.2.exe /

RUN Write-Host "Installing may take some time..."                 ; \
    Start-Process -FilePath '\Firefox Setup 58.0.2.exe'             \
                  -ArgumentList '/S'                                \
                  -Wait                                           ; \
    SetX /M MOZ_HEADLESS 1                                        ; \
    Remove-Item '/Firefox Setup 58.0.2.exe'



#
# Install GeckoDriver
#
ADD https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-win64.zip /

RUN Expand-Archive -Path '/geckodriver-v0.25.0-win64.zip'           \
                   -DestinationPath /                             ; \
    Move-Item /geckodriver.exe '/Program Files/Mozilla Firefox'   ; \
    Remove-Item '/geckodriver-v0.25.0-win64.zip'