#
# Use winver to check whether your OS is >= 1909
# If not, use the appropriate version
#
FROM mcr.microsoft.com/windows:1909



#
# Configure Powershell as the Default Shell
#
SHELL ["PowerShell", "-NoProfile", "-Command", "$ErrorActionPreference = 'Stop';"]
CMD PowerShell.exe



#
# Install Chrome
#
ADD https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Win_x64%2F737173%2Fchrome-win.zip?generation=1580439619624464&alt=media /

RUN Expand-Archive -Path '/chrome-win.zip'                                                   \
                   -DestinationPath '/'                                                    ; \
    New-Item       -Path '/Program Files (x86)/Google/Chrome/Application'                    \
                   -ItemType Directory                                                     ; \
    Get-ChildItem  -Path '/chrome-win' |                                                     \
    Move-Item      -Destination '/Program Files (x86)/Google/Chrome/Application'           ; \
    Remove-Item    -Path '/chrome-win'                                                     ; \
    Remove-Item    -Path '/chrome-win.zip'



#
# Install ChromeDriver
#
ADD https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Win_x64%2F737173%2Fchromedriver_win32.zip?generation=1580439625877582&alt=media /

RUN Expand-Archive -Path '/chromedriver_win32.zip'                                           \
                   -DestinationPath '/'                                                    ; \
    Get-ChildItem  -Path '/chromedriver_win32' |                                             \
    Move-Item      -Destination '/Program Files (x86)/Google/Chrome/Application'           ; \
    Remove-Item    -Path '/chromedriver_win32'                                             ; \
    Remove-Item    -Path '/chromedriver_win32.zip'
